plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${fabric_loom_version}"
}

base {
    archivesName = "${mod_id}-fabric"
}

version = rootProject.mod_version
group = rootProject.mod_group_id

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "SableCompanion"
                url = "https://maven.ryanhcode.dev/releases"
            }
        }
        filter {
            includeGroup("dev.ryanhcode.sable-companion")
        }
    }

    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/releases"
    }
}

loom {
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    modCompileOnly "com.terraformersmc:modmenu:11.0.3"
    modRuntimeOnly "com.terraformersmc:modmenu:11.0.3"

    include(modApi("dev.ryanhcode.sable-companion:sable-companion-fabric-1.21.1:${rootProject.sable_companion_version}"))
}

sourceSets.main.java {
    srcDir("../common/src/main/java")
}

sourceSets.main.resources {
    srcDir("../common/src/main/resources")
}

def modVersion = project.version.toString()

processResources {
    inputs.property "version", modVersion

    filesMatching("fabric.mod.json") {
        expand "version": modVersion
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}
