modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/NotBerryYummy/ThirdCross"
issueTrackerURL="https://github.com/NotBerryYummy/ThirdCross/issues"
authors="NotBerryYummy"
description='''
ThirdCross adds configurable first- and third-person crosshairs, including an aim-point crosshair that follows blocks and entities.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
