plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.144'
}

version = rootProject.mod_version
group = rootProject.mod_group_id

sourceSets.main.java {
    srcDir('../common/src/main/java')
}

sourceSets.main.resources {
    srcDir('src/generated/resources')
    srcDir('../common/src/main/resources')
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = 'SableCompanion'
                url = 'https://maven.ryanhcode.dev/releases'
            }
        }
        filter {
            includeGroup('dev.ryanhcode.sable-companion')
        }
    }
}

base {
    archivesName = "${rootProject.mod_id}-neoforge"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = rootProject.neo_version

    parchment {
        mappingsVersion = rootProject.parchment_mappings_version
        minecraftVersion = rootProject.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', rootProject.mod_id
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${rootProject.mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    jarJar(api("dev.ryanhcode.sable-companion:sable-companion-common-1.21.1:[${rootProject.sable_companion_version},)")) {
        version {
            prefer(rootProject.sable_companion_version)
        }
    }
}

def metadataProperties = [
        minecraft_version      : rootProject.minecraft_version,
        minecraft_version_range: rootProject.minecraft_version_range,
        neo_version            : rootProject.neo_version,
        loader_version_range   : rootProject.loader_version_range,
        mod_id                 : rootProject.mod_id,
        mod_name               : rootProject.mod_name,
        mod_license             : rootProject.mod_license,
        mod_version            : rootProject.mod_version,
]

def generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    inputs.properties metadataProperties
    expand metadataProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.named('processResources', ProcessResources).configure {
    from('../LICENSE')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
